### ISSUE TITLE
Repo is becoming dustbin

### ISSUE THREAD

**Issue by PSKP-95** [srinidhibhat45/HelloWorldCollections#12]
We should stop putting all code in the root folder. 

We can create a **folder for each language and put a code file and README.md** with a small description about the language (You can copy from Wikipedia).

I am doing it for java and bash

**Comment by srinidhibhat45** [comment]
hey @PSKP-95 just looking for hello world files, so it's fine being in the root folder, I don't mind.

**Comment by PSKP-95** [comment]
Ok @srinidhibhat45  I will do that for all languages.

**Comment by PSKP-95** [comment]
@srinidhibhat45 Hi https://github.com/srinidhibhat45/HelloWorldCollections/pull/13 pull request will close this issue.
